# Generated by Django 3.2.4 on 2021-06-27 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 6, 27, 13, 25, 15, 86060, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
